### ISSUE TITLE
Date parsed with wrong format (Nighthawk M1 modem)

### ISSUE THREAD

**Issue by code-to-joy** [amelchio/eternalegypt#19]
This seems to be specific for the Netgear MR1100 (Nighthawk M1) device.

A date returned from the modem is formatted differently from what the code is expecting. I'm not sure if this is a change in how the modem returns date between this model (M1) and the other supported models, or if this was simply an bug that did not show up except when the date was with a day that was more than 12 (which is when the error occurs). It could also be a regionale setting in the modem, but I cannot verify that. 

The date returned from the modem in this scenario is "11/29/19 08:29:51 AM" - equivalent to Month-Day-Year, and so on. The script expects Day-Month-Year. 

Error: 
`
Traceback (most recent call last):
  File "C:\Code\eternalegypt-master\eternalegypt-master\examples\status.py", line 55, in <module>
    asyncio.get_event_loop().run_until_complete(get_information())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Code\eternalegypt-master\eternalegypt-master\examples\status.py", line 24, in get_information
    result = await modem.information()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\eternalegypt\eternalegypt.py", line 62, in wrapper
    return await function(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\eternalegypt\eternalegypt.py", line 276, in information
    result = self._build_information(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\eternalegypt\eternalegypt.py", line 251, in _build_information
    dt = datetime.strptime(msg['rxTime'], '%d/%m/%y %I:%M:%S %p')
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '11/29/19 08:29:51 AM' does not match format '%d/%m/%y %I:%M:%S %p'`

Steps to reproduce:
1. Apply fix for issue #18 (https://github.com/amelchio/eternalegypt/issues/18), or else you will never reach this part of the code
2. Run script status.py against a Netgear Nighthawk M1 modem

**Comment by amelchio** [comment]
We can of course handle this exception but that would mean that dates within the first 12 days of each month would be converted incorrectly. It would be good to find a way to distinguish between the two situations and do different conversions in each case.

If you can e-mail me the full content of `data`, I can compare it to mine and maybe I can spot something?

**Comment by code-to-joy** [comment]
> We can of course handle this exception but that would mean that dates within the first 12 days of each month would be converted incorrectly. It would be good to find a way to distinguish between the two situations and do different conversions in each case.

Yes, I agree. 
 
> If you can e-mail me the full content of `data`, I can compare it to mine and maybe I can spot something?

I sent you the output of modem.information, in raw format.

**Comment by amelchio** [comment]
Yeah, that should work. Thanks.

**Comment by amelchio** [comment]
I don't see anything that could decide this in general (like a regional setting), so I now select the expected time format based on the model of the modem.

However, I have now realized that the Home Assistant integration does not even use the timestamp so it probably does not matter much :)
